"""add boards and board members

Revision ID: 102475f674ca
Revises: 4a565ba8efc4
Create Date: 2026-08-30 11:42:57.700304

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102475f674ca'
down_revision: str | Sequence[str] | None = '4a565ba8efc4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boards'))
    )
    op.create_table('board_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'member')", name=op.f('ck_board_members_role')),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_board_members_actor_id_actors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_board_members_board_id_boards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_members')),
    sa.UniqueConstraint('board_id', 'actor_id', name='uq_board_members_board_id_actor_id')
    )
    op.create_index(op.f('ix_board_members_actor_id'), 'board_members', ['actor_id'], unique=False)
    op.create_index(op.f('ix_board_members_board_id'), 'board_members', ['board_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_members_board_id'), table_name='board_members')
    op.drop_index(op.f('ix_board_members_actor_id'), table_name='board_members')
    op.drop_table('board_members')
    op.drop_table('boards')
    # ### end Alembic commands ###
