"""add agents and agent api keys

Revision ID: 18dc3e2f3ef0
Revises: b8947ed14888
Create Date: 2026-08-30 16:52:57.259450

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18dc3e2f3ef0'
down_revision: str | Sequence[str] | None = 'b8947ed14888'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_person_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_agents_actor_id_actors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_person_id'], ['people.actor_id'], name=op.f('fk_agents_owner_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id', name=op.f('pk_agents'))
    )
    op.create_index(op.f('ix_agents_owner_person_id'), 'agents', ['owner_person_id'], unique=False)
    op.create_table('agent_api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.actor_id'], name=op.f('fk_agent_api_keys_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_api_keys')),
    sa.UniqueConstraint('prefix', name=op.f('uq_agent_api_keys_prefix'))
    )
    op.create_index(op.f('ix_agent_api_keys_agent_id'), 'agent_api_keys', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_api_keys_agent_id'), table_name='agent_api_keys')
    op.drop_table('agent_api_keys')
    op.drop_index(op.f('ix_agents_owner_person_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
