"""add actors, people and sessions

Revision ID: 4a565ba8efc4
Revises: b87ec1895af4
Create Date: 2026-08-30 11:27:44.288424

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a565ba8efc4'
down_revision: str | Sequence[str] | None = 'b87ec1895af4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actors'))
    )
    op.create_table('people',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_people_actor_id_actors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id', name=op.f('pk_people')),
    sa.UniqueConstraint('email', name=op.f('uq_people_email'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_sessions_actor_id_actors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_index(op.f('ix_sessions_actor_id'), 'sessions', ['actor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_actor_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('people')
    op.drop_table('actors')
    # ### end Alembic commands ###
