"""add cards

Revision ID: b8947ed14888
Revises: b8d7a3b4161c
Create Date: 2026-08-30 12:21:50.767233

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8947ed14888'
down_revision: str | Sequence[str] | None = 'b8d7a3b4161c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('column_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('created_by_actor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_cards_board_id_boards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['column_id'], ['board_columns.id'], name=op.f('fk_cards_column_id_board_columns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_actor_id'], ['actors.id'], name=op.f('fk_cards_created_by_actor_id_actors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cards')),
    sa.UniqueConstraint('column_id', 'position', deferrable=True, initially='DEFERRED', name='uq_cards_column_id_position')
    )
    op.create_index(op.f('ix_cards_board_id'), 'cards', ['board_id'], unique=False)
    op.create_index(op.f('ix_cards_column_id'), 'cards', ['column_id'], unique=False)
    op.create_index(op.f('ix_cards_created_by_actor_id'), 'cards', ['created_by_actor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_created_by_actor_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_column_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_board_id'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
