"""add board columns

Revision ID: b8d7a3b4161c
Revises: 102475f674ca
Create Date: 2026-08-30 11:57:42.739240

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d7a3b4161c'
down_revision: str | Sequence[str] | None = '102475f674ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_columns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('wip_limit', sa.Integer(), nullable=True),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('wip_limit IS NULL OR wip_limit > 0', name=op.f('ck_board_columns_wip_limit_positive')),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_board_columns_board_id_boards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_columns')),
    sa.UniqueConstraint('board_id', 'position', deferrable=True, initially='DEFERRED', name='uq_board_columns_board_id_position')
    )
    op.create_index(op.f('ix_board_columns_board_id'), 'board_columns', ['board_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_columns_board_id'), table_name='board_columns')
    op.drop_table('board_columns')
    # ### end Alembic commands ###
